[build-system]
requires = ["setuptools>=68", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "velto-lang"
version = "0.84.0"
description = "Velto programming language"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Rishu132024-create"}
]
keywords = [
    "velto",
    "programming-language",
    "interpreter",
    "language"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/rishu132024-create/velto"
Repository = "https://github.com/rishu132024-create/velto"
Issues = "https://github.com/rishu132024-create/velto/issues"

[project.scripts]
velto = "velto_cli:main"
