import os
import sys


def extract_documentation(source, filename):
    lines = source.splitlines()

    title = os.path.splitext(
        os.path.basename(filename)
    )[0]

    functions = []
    variables = []

    for number, raw_line in enumerate(lines, 1):
        line = raw_line.strip()

        if not line:
            continue

        if line.startswith("func "):
            name = line[5:].strip()

            if name.endswith(":"):
                name = name[:-1].strip()

            functions.append(
                {
                    "name": name,
                    "line": number
                }
            )

        if "=" in line:
            left = line.split("=", 1)[0].strip()

            if left.isidentifier():
                variables.append(
                    {
                        "name": left,
                        "line": number
                    }
                )

    return {
        "title": title,
        "functions": functions,
        "variables": variables,
        "lines": len(lines)
    }


def generate_markdown(data):
    output = []

    output.append(
        "# " + data["title"]
    )

    output.append("")

    output.append(
        "Generated by Velto Documentation Generator."
    )

    output.append("")

    output.append("## Overview")

    output.append("")

    output.append(
        "Source lines: "
        + str(data["lines"])
    )

    output.append("")

    output.append("## Functions")

    output.append("")

    if data["functions"]:
        for function in data["functions"]:
            output.append(
                "- `"
                + function["name"]
                + "` — line "
                + str(function["line"])
            )
    else:
        output.append(
            "No functions found."
        )

    output.append("")

    output.append("## Variables")

    output.append("")

    if data["variables"]:
        for variable in data["variables"]:
            output.append(
                "- `"
                + variable["name"]
                + "` — line "
                + str(variable["line"])
            )
    else:
        output.append(
            "No variables found."
        )

    output.append("")

    return "\n".join(output)


def generate_file(source_path, output_path):
    with open(
        source_path,
        "r",
        encoding="utf-8"
    ) as file:
        source = file.read()

    data = extract_documentation(
        source,
        source_path
    )

    markdown = generate_markdown(
        data
    )

    output_directory = os.path.dirname(
        os.path.abspath(output_path)
    )

    os.makedirs(
        output_directory,
        exist_ok=True
    )

    with open(
        output_path,
        "w",
        encoding="utf-8"
    ) as file:
        file.write(markdown)


def main():
    if len(sys.argv) < 2:
        print(
            "Usage: python velto_docs.py <file.vlt> [output.md]"
        )
        return 1

    source_path = sys.argv[1]

    if not os.path.isfile(source_path):
        print(
            "Velto Documentation Error: "
            "File not found"
        )
        return 1

    if len(sys.argv) >= 3:
        output_path = sys.argv[2]
    else:
        base = os.path.splitext(
            os.path.basename(source_path)
        )[0]

        output_path = os.path.join(
            "docs",
            base + ".md"
        )

    try:
        generate_file(
            source_path,
            output_path
        )
    except Exception as error:
        print(
            "Velto Documentation Error:",
            error
        )
        return 1

    print(
        "Documentation generated:",
        output_path
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
